services:
  sui_blackjack_api:
    build: .
    expose:
      - 8080
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
    env_file:
      - .env
    # environment:
    #   ADMIN_SECRET_KEY: ${TEST}
